### ISSUE TITLE
缺少data里的文件

### ISSUE THREAD

**Issue by 1148270327** [xzp27/BERT-for-Chinese-Question-Answering#5]
你好，方便给出data内的文件吗？好像不止缺少训练语料，常规的bert配置文件也缺少

**Comment by xzp27** [comment]
抱歉不能提供数据，配置文件在https://github.com/google-research/bert可下载

**Comment by eva-n27** [comment]
抱歉不能提供数据，配置文件在https://github.com/google-research/bert 可下载
