### ISSUE TITLE
你的modeling.py中缺少BertForPreTraining()类，无法将tensorflow模型文件转化为pytorch文件

### ISSUE THREAD

**Issue by LouZhiX** [xzp27/BERT-for-Chinese-Question-Answering#6]

**Comment by LouZhiX** [comment]
需要将BertForPreTraining类加入

**Comment by eva-n27** [comment]
[convert_tf_checkpoint_to_pytorch.py](https://github.com/xzp27/BERT-for-Chinese-Question-Answering/blob/master/convert_tf_checkpoint_to_pytorch.py) 了解一下

**Comment by LouZhiX** [comment]
![image](https://user-images.githubusercontent.com/24652283/55723897-c28bf300-5a3c-11e9-9fe5-91c9808ebcaf.png)

**Comment by LouZhiX** [comment]
这个.modeling好像无法编译通过吧？

**Comment by eva-n27** [comment]
https://github.com/xzp27/BERT-for-Chinese-Question-Answering/blob/ef2761455fbfbe23a8ca368d677c19beea5f04ba/run_squad.py#L38
本仓库中的代码中应该没有图片中的这行呀，我使用的huggingface的代码版本可能比较早，和你使用的应该不一样吧

**Comment by LouZhiX** [comment]
这一行代码是在convert_tf_checkpoint_to_pytorch中，run_squad中的代码是没错的

**Comment by LouZhiX** [comment]
目前是在tensorflow的ckpt预训练模型转化为pytorch模型上出现了问题

**Comment by eva-n27** [comment]
了解了，发现是忘记上传修改后的convert_tf_checkpoint_to_pytorch.py，请稍等我更新一下

**Comment by LouZhiX** [comment]
好的，谢谢

**Comment by eva-n27** [comment]
已将huggingface原始版本的convert_tf_checkpoint_to_pytorch.py上传，应该可以用了
