### ISSUE TITLE
这个地方新建文件夹出现错误，参数设定里面没有出现args.ft_dir

### ISSUE THREAD

**Issue by LouZhiX** [xzp27/BERT-for-Chinese-Question-Answering#7]
https://github.com/xzp27/BERT-for-Chinese-Question-Answering/blob/0871022bffee4d134765978aeb6f34b1244a7188/run_squad.py#L908

**Comment by eva-n27** [comment]
https://github.com/xzp27/BERT-for-Chinese-Question-Answering/blob/58c62f9baf34510d441834fa743b616372abf574/run_squad.py#L908
已更新，谢谢指正
